config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'posts#index'
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :destroy, :edit, :update]
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <!-- Navbar content -->
  <%= link_to 'English Dairy', "/", class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <% if user_signed_in? %>
          <li><%= link_to current_user.nickname, user_path(current_user), class: "header-text" %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "header-text" %> </li> 
        <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path, class: "header-text" %></li>
          <li><%= link_to 'Log In', new_user_session_path, class: "header-text" %></li>
        <% end %>
      </li>
        <% if user_signed_in? %>
          <li class="nav-item">
           <%= link_to 'New post', new_post_path, class: "header-text" %>
          </li>
        <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/shared/_mypage_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <!-- Navbar content -->
  <%= link_to 'English Dairy', "/", class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <% if user_signed_in? %>
          <li><%= link_to current_user.nickname, user_path(current_user), class: "header-text" %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "header-text" %> </li> 
        <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path, class: "header-text" %></li>
          <li><%= link_to 'Log In', new_user_session_path, class: "header-text" %></li>
        <% end %>
      </li>
        <% if user_signed_in? %>
          <li class="nav-item">
           <%= link_to 'New post', new_post_path, class: "header-text" %>
          </li>
        <% end %>
        <% if user_signed_in? && @user.id == current_user.id %>
          <li class="nav-item">
           <%= link_to 'Edit Profiel', edit_user_path, method: :get, class: "header-text" %>
           <%= link_to 'Cansel membership', user_path(@user.id), method: :delete, class: "header-text"%>
          </li>
        <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/shared/_second_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <!-- Navbar content -->
  <%= link_to 'English Dairy', "/", class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <% if user_signed_in? %>
          <li><%= link_to current_user.nickname, user_path(current_user), class: "header-text" %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "header-text" %> </li> 
        <% else %>
          <li><%= link_to @post.user.nickname, '/users/show', class: "header-text"%></li>
          <li><%= link_to 'Sign Up', new_user_registration_path, class: "header-text" %></li>
          <li><%= link_to 'Log In', new_user_session_path, class: "header-text" %></li>
        <% end %>
      </li>
        <% if user_signed_in? %>
          <li class="nav-item">
           <%= link_to 'New post', new_post_path, class: "header-text" %>
          </li>
        <% end %>
        <% if user_signed_in? && @post.user_id == current_user.id %>
          <li class="nav-item">
           <%= link_to 'Edit', edit_post_path, method: :get, class: "header-text" %>
           <%= link_to 'Delete', post_path(@post.id), method: :delete, class: "header-text" %>
          </li>
        <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>