config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'posts#index'
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :destroy, :edit, :update]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :post_tags
  has_many :tags, through: :post_tags, dependent: :destroy
  has_one_attached :image
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :destroy]
  before_action :move_to_index, except: [:index, :show]

  def index
    @posts = Post.all.order(id: 'DESC')
  end

  def new
    @form = PostsTag.new
  end

  def create
    @form = PostsTag.new(post_params)
    if  @form.valid? 
      @form.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def edit
    load_post
    @form = PostsTag.new(post: @post)
  end

  def update
    load_post
    @form = PostsTag.new(post_params, post: @post)
    if  @form.valid? 
      @form.save
      redirect_to post_path
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  private

  def post_params
    params.require(:post).permit(:image, :title, :text, :name).merge(user_id: current_user.id)
  end

  def load_post
    @post = current_user.posts.find(params[:id])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: form, local: true) do |f| %>
    <%# エラーメッセージ表示 %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="post-form">
      <%# 投稿フォーム %>
      <div class="img-upload">
        <%= f.file_field :image, class:"img-form", id:"post-image" %>
      </div>

      <div class="new-post">
        <%= f.text_area :title, class:"title-text", id:"title", placeholder:"Title", maxlength:"40" %>
      </div>
      <div class="new-post">
        <%= f.text_area :text, class:"post-text", id:"text", placeholder:"text", maxlength:"1000" %>
      </div>
      <div class="new-post">
        <%= f.text_area :name, class:"tag-text", id:"tag", placeholder:"tags. Please separete by commmas.", maxlength:"30" %>
      </div>
      <div class="post-btn-contents">
        <%= f.submit "Post" ,class:"post-btn" %>
        <%= link_to 'Return to home', root_path, class:"back-btn"%>
      </div>
    </div>
  <% end %>

app/views/posts/edit.html.erb
<%= render "shared/second_header"%>

<div class="post-main">
  <h2 class="post-main-title">
    Edit a Diary
  </h2>

  <%= render partial: "form", locals: {form: @form} %>
</div>

app/views/posts/index.html.erb
<%= render "shared/header"%>
<div class="main">

  <div class="notifications">
    <div class="notice"><%= flash[:message] %></div>
  </div> 
  <%# 投稿表示 %>
  <div class="post-content">
    <h2 class="title">Post List</h2>
    <ul class="post-lists">
      <% @posts.each do |post|%>
        <li class="list">
          <%= link_to post_path(post.id), method: :get do %>
            <div class="post-image-content">
              <%= image_tag post.image, class: "post-image" if post.image.attached?%>
            </div>
          <% end %> 
            <div class="post-info">
              <h3 class="post-title">
                <%= post.title%>
              </h3>
            </div>
        </li>
      <% end %>
    </ul>
  </div>

  <%# ダミー画像 %>
  <% if @posts.blank? %>
    <div class="post-lists">
      <div class="list">
        <div class="img">
          <img src="https://images.unsplash.com/photo-1496284427489-f59461d8a8e6?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjF9">
        </div>
        <div class="post-info">
          <h3 class="post-title">
            The title will be include
          </h3>
        </div>
      </div>
      <div class="list">
        <div class="img">
          <img src="https://images.unsplash.com/photo-1496284427489-f59461d8a8e6?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjF9">
        </div>
        <div class="post-info">
          <h3 class="post-title">
            The title will be include
          </h3>
        </div>
      </div>
      <div class="list">
        <div class="img">
          <img src="https://images.unsplash.com/photo-1496284427489-f59461d8a8e6?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjF9">
        </div>
        <div class="post-info">
          <h3 class="post-title">
            The title will be include
          </h3>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render "shared/header"%>

<div class="post-main">
  <h2 class="post-main-title">
    Wirte a diary in English
  </h2>

  <%= render partial: "form", locals: {form: @form} %>
</div>

app/views/posts/show.html.erb
<%= render "shared/second_header"%>
<div class="show-main">
  <div class="show-contents">
    <div class="show-content">
      <div class="post-image-content">
        <%= image_tag @post.image, class: "post-image"%>
      </div>
      <%# タグの表示 %>
      <div class="post-tag-content">
        <div class="post-tag">
          <%@post.tags.each do |tag| %>
            #<%=tag.name%>
          <%end%>
        </div>
      </div>  
      <div class="post-container">
        <p class="post-title"><%= @post.title %></p>
        <p><%= simple_format(@post.text) %></p>
        <p><%= link_to @post.user.nickname, "/users/#{@post.user_id}" %></p>
      </div>
      <div class="comment-lists">
          <p>＜comment list＞</p>
          <% if @comments %>
            <% @post.comments.each do |comment| %>
              <p class="comment-list">
                <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
                <%= comment.comment %>
              </p>
              <% if user_signed_in? && comment.user_id == current_user.id %>
                <p><%= link_to 'Comment Delete', post_comment_path(@post, comment), method: :delete %></p>
              <% end %>
            <% end %>
          <% end %>
      </div>
      <div class="comment-form-content">
        <% if user_signed_in? %>
          <%= form_with model: [@post, @comment], local: true do |f| %>
            <p><%= f.text_field :comment , class: "comment-form", placeholder: "comment" %></p>
            <p><%= f.submit "SEND", class: "comment-btn" %></p>
          <% end %>
        <% end %>
      </div>  
    </div>
</div>